### ISSUE TITLE
 /BioII/lulab_b/taoyuhuan/cfRNAseq/reference and tools

### ISSUE THREAD

**Issue by yuanG2000** [tyh-19/Pipeline-for-multiomics#1]
hello, i wonder What is the file in this path，or how to generate  them.
thanks a lot 
![d53ea62b7b23dbfdea6d0b72b89282f](https://github.com/tyh-19/Pipeline-for-multiomics/assets/154750598/bb86abdb-cfbd-45bd-ba95-ebe544f459ae)

**Comment by tyh-19** [comment]
Thanks for reminding. I have uploaded the reference files to a cloud storage (which are too large to be included in github). Here is the link for downloading: https://cloud.tsinghua.edu.cn/d/32d6cf0e8f2045218671/

**Note**: Files in reference/genome_index/star/hg38_long/ are too large to share (~29G), but you can generate the index files by the following command using STAR_2.5.3a: 
STAR --runMode genomeGenerate --genomeDir ~/reference/genome_index/star/hg38_long/ \
		--genomeFastaFiles ~/reference/reference_genome/fasta/hg38.fa \
		--sjdbGTFfile ~/reference/gtf/long_RNA.gtf \
		--sjdbOverhang 149 \
		--runThreadN 20

The following is all files contained in the reference directory:
reference/
├── bed
│   ├── antisense.bed
│   ├── enhancer.bed
│   ├── exon.bed
│   ├── gene.bed
│   ├── intron.bed
│   ├── lncRNA.bed
│   ├── miRNA.bed
│   ├── mRNA.bed
│   ├── mRNA-Mt.bed
│   ├── mRNA-noMt.bed
│   ├── Mt_RNA_37.bed
│   ├── piRNA.bed
│   ├── priority.txt
│   ├── promoter.bed
│   ├── pseudogene.bed
│   ├── repeats.bed
│   ├── snoRNA.bed
│   ├── snRNA.bed
│   ├── srpRNA.bed
│   ├── tRNA.bed
│   ├── tucpRNA.bed
│   └── Y_RNA.bed
├── fasta
│   ├── chrom.size
│   ├── hg38.dict
│   ├── hg38.fa
│   └── hg38.fa.fai
├── genome_index
│   └── star
│       ├── circRNA
│       │   ├── chrLength.txt
│       │   ├── chrNameLength.txt
│       │   ├── chrName.txt
│       │   ├── chrStart.txt
│       │   ├── Genome
│       │   ├── genomeParameters.txt
│       │   ├── SA
│       │   └── SAindex
│       **├── hg38_long
│       │   ├── chrLength.txt
│       │   ├── chrNameLength.txt
│       │   ├── chrName.txt
│       │   ├── chrStart.txt
│       │   ├── exonGeTrInfo.tab
│       │   ├── exonInfo.tab
│       │   ├── geneInfo.tab
│       │   ├── Genome
│       │   ├── genomeParameters.txt
│       │   ├── Log.out
│       │   ├── SA
│       │   ├── SAindex
│       │   ├── sjdbInfo.txt
│       │   ├── sjdbList.fromGTF.out.tab
│       │   ├── sjdbList.out.tab
│       │   └── transcriptInfo.tab**
│       ├── mature_miRNA
│       │   ├── chrLength.txt
│       │   ├── chrNameLength.txt
│       │   ├── chrName.txt
│       │   ├── chrStart.txt
│       │   ├── Genome
│       │   ├── genomeParameters.txt
│       │   ├── SA
│       │   └── SAindex
│       ├── miRNA
│       │   ├── chrLength.txt
│       │   ├── chrNameLength.txt
│       │   ├── chrName.txt
│       │   ├── chrStart.txt
│       │   ├── Genome
│       │   ├── genomeParameters.txt
│       │   ├── SA
│       │   └── SAindex
│       ├── rRNA
│       │   ├── chrLength.txt
│       │   ├── chrNameLength.txt
│       │   ├── chrName.txt
│       │   ├── chrStart.txt
│       │   ├── Genome
│       │   ├── genomeParameters.txt
│       │   ├── SA
│       │   └── SAindex
│       ├── spikein_long
│       │   ├── Aligned.out.bam
│       │   ├── chrLength.txt
│       │   ├── chrNameLength.txt
│       │   ├── chrName.txt
│       │   ├── chrStart.txt
│       │   ├── Genome
│       │   ├── genomeParameters.txt
│       │   ├── Log.out
│       │   ├── Log.progress.out
│       │   ├── SA
│       │   ├── SAindex
│       │   ├── _STARtmp
│       │   ├── Unmapped.out.mate1
│       │   └── Unmapped.out.mate2
│       ├── spikein_small
│       │   ├── chrLength.txt
│       │   ├── chrNameLength.txt
│       │   ├── chrName.txt
│       │   ├── chrStart.txt
│       │   ├── Genome
│       │   ├── genomeParameters.txt
│       │   ├── SA
│       │   └── SAindex
│       └── univec
│           ├── chrLength.txt
│           ├── chrNameLength.txt
│           ├── chrName.txt
│           ├── chrStart.txt
│           ├── Genome
│           ├── genomeParameters.txt
│           ├── SA
│           └── SAindex
└── gtf
    ├── long_RNA.gtf
    └── reference_genes.txt

**Comment by yuanG2000** [comment]
thx!
i have downloaded all files,they help me a lot.

**Comment by tyh-19** [comment]
OK, i will close this issue.
